services:
  - type: web
    name: compass-backend
    env: python
    region: oregon
    buildCommand: |
      pip install -r requirements.txt
      python scripts/build_index.py
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.1
      - key: OPENAI_API_KEY
        sync: false
      - key: CORS_ORIGINS
        sync: false
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1

  - type: web
    name: compass-frontend
    env: node
    region: oregon
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NODE_VERSION
        value: 18.19.0
      - key: NEXT_PUBLIC_API_URL
        sync: false 